package com.kola.moneypal.utils

object PayementConfiguration {

    val ID_ACTION_PAYEMENT_ORANGE_MONEY = "d68d2e79"
    val ETAPE_1_PAYEMENT_ORANGE_MONEY ="1"
    val ETAPE_2_PAYEMENT_ORANGE_MONEY ="2"
    val REQUEST_CODE_FOR_PAYEMENY_ORANGE_MONEY = 50


    val ID_ACTION_PAYEMENT_ORANGE_MONEY_VERS_MTN = "c3494999"
    val ETAPE_1_PAYEMENT_ORANGE_MONEY_VERS_MTN ="1"
    val ETAPE_2_PAYEMENT_ORANGE_MONEY_VERS_MTN ="2"
}